### ISSUE TITLE
Path from example parsed wrong

### ISSUE THREAD

**Issue by rpoelstra** [richardpiazza/SwiftSVG#3]
Hi,

I'm using your parser with an example file from w3.org: [quad01](https://www.w3.org/TR/SVG/images/paths/quad01.svg)

I noticed that for the main path (with the quadratic curves), there is a parse error:
The path contains the 'T' command, but the second curve segment is not present in the path output from your parser. Instead it seems to be replaced with a 'close path' command.

**Comment by richardpiazza** [comment]
@rpoelstra Thanks so much for logging this issue. I've been working on a fix along with a couple of other corrections. Having the example file really helped!

**Comment by rpoelstra** [comment]
Thanks for fixing this. I can confirm that the path is now handled correctly.
I noticed though that the `fill` property of the path returns a valid struct, while the `fillColor` is "none". I think I would expect a nil `fill`, as "none" indicates that it should not be filled. Is this intended behaviour?
On a side note, do you plan to support css style `style` properties on paths?

**Comment by richardpiazza** [comment]
Arguments could be made in either direction in regards to the `fillColor`.

I think I prefer the current implementation where by the information is preserved by having `none` as the value for `fillColor`. If this were simply `nil`, then there is ambiguity. Is `nil` the representation that there was _no_ attribute in the XML, or is `nil` the representation that the attribute value indicated the lack of another value? I see `none` as a valid value for that `fill` attribute (none/clear/transparent).

I believe the css style attribute values are preserved, but at the moment, they are not processed to override any of the other values. Could be a valuable feature! Feel free to open another issue/feature request for that (_although not sure when I'll have some more time to get around to it_)

**Comment by rpoelstra** [comment]
I totally agree about `fillColor`, but as I understand your code, the `fill` attribute is some kind of aggregate property which you already make `nil` under certain conditions. So I was wondering whether `fillColor = "none"` would be a proper reason to make `fill` equal to `nil`. Not `fillColor`, that one should remain "none" indeed :).
