### ISSUE TITLE
Some issues with smooth curves

### ISSUE THREAD

**Issue by rpoelstra** [richardpiazza/SwiftSVG#9]
Hi,

I found some issues with the smooth curves. Please see the attached patch for improvements.

The SVG documentation also has a much easier way of calculating the reflection point. I've added it in here as well.

[SwiftSVG-90cb6d2-Improved smooth quadratic and cubic curves..patch](https://github.com/richardpiazza/SwiftSVG/files/11044313/SwiftSVG-90cb6d2-Improved.smooth.quadratic.and.cubic.curves.patch)

**Comment by richardpiazza** [comment]
Great... I'll take a look when I have a moment. Yeah, I saw your _beautifully reduced_ reflection changes, and incorporated that into my other library that I will pull an update for (https://github.com/richardpiazza/Swift2D/blob/f9e993c0075013339c5c132ab01fc78750b8774f/Sources/Swift2D/Point%2BComputed.swift#L15)
